// SAP2000 OAPI proof of concept: write a .s2k, attach or start SAP, open, run, pull results.
// C# 5, compiled by Add-Type under Windows PowerShell 5.1 against SAP2000v1.dll (the .NET
// interop assembly shipped in the SAP2000 install folder). Mirrors pythonTools/.../sap_api.py.
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using SAP2000v1;

public class SapPoc
{
    const string ProgId = "CSI.SAP2000.API.SapObject";
    static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    public cOAPI Sap;
    public cSapModel Model;
    public bool Started;

    // Attach to a running SAP2000, else start the one at exePath.
    public static SapPoc AttachOrStart(string exePath)
    {
        SapPoc s = new SapPoc();
        try { s.Sap = (cOAPI)Marshal.GetActiveObject(ProgId); }
        catch (COMException)
        {
            cHelper helper = new Helper();
            s.Sap = helper.CreateObject(exePath);
            Check(s.Sap.ApplicationStart(), "ApplicationStart");
            s.Sap.Visible();
            s.Started = true;
        }
        s.Model = s.Sap.SapModel;
        return s;
    }

    // Simply supported beam, kip-ft: span L, point load P at midspan (two frames, load at joint 2).
    // Hand check: R = P/2 at each end, M = P*L/4 at joint 2.
    // version: stamp the file with the SAP that will read it -- SAP 26 silently imports NOTHING
    // from a file stamped 22.0.0 (OpenFile still returns 0), so never hard-code it.
    public static void WriteBeamS2k(string path, string version, double L, double P)
    {
        string[] lines = {
            "File generated by SapPoc.cs (Pluto)", "",
            "TABLE:  \"PROGRAM CONTROL\"",
            "   ProgramName=SAP2000   Version=" + version + "   CurrUnits=\"Kip, ft, F\"   MergeTol=0.001", "",
            "TABLE:  \"MATERIAL PROPERTIES 01 - GENERAL\"",
            "   Material=STEEL   Type=Steel   SymType=Isotropic   TempDepend=No   Color=Cyan", "",
            "TABLE:  \"MATERIAL PROPERTIES 02 - BASIC MECHANICAL PROPERTIES\"",
            "   Material=STEEL   UnitWeight=0.49   UnitMass=0.0152   E1=4176000   G12=1606154   U12=0.3   A1=6.5e-06", "",
            "TABLE:  \"FRAME SECTION PROPERTIES 01 - GENERAL\"",
            "   SectionName=BEAM   Material=STEEL   Shape=Rectangular   t3=2   t2=1   Color=Yellow", "",
            "TABLE:  \"JOINT COORDINATES\"",
            "   Joint=1   CoordSys=GLOBAL   CoordType=Cartesian   XorR=0   Y=0   Z=0",
            F("   Joint=2   CoordSys=GLOBAL   CoordType=Cartesian   XorR={0}   Y=0   Z=0", L / 2),
            F("   Joint=3   CoordSys=GLOBAL   CoordType=Cartesian   XorR={0}   Y=0   Z=0", L), "",
            "TABLE:  \"CONNECTIVITY - FRAME\"",
            "   Frame=1   JointI=1   JointJ=2   IsCurved=No",
            "   Frame=2   JointI=2   JointJ=3   IsCurved=No", "",
            "TABLE:  \"FRAME SECTION ASSIGNMENTS\"",
            "   Frame=1   SectionType=Rectangular   AutoSelect=N.A.   AnalSect=BEAM   DesignSect=BEAM   MatProp=Default",
            "   Frame=2   SectionType=Rectangular   AutoSelect=N.A.   AnalSect=BEAM   DesignSect=BEAM   MatProp=Default", "",
            "TABLE:  \"JOINT RESTRAINT ASSIGNMENTS\"",
            "   Joint=1   U1=Yes   U2=Yes   U3=Yes   R1=Yes   R2=No   R3=No",
            "   Joint=3   U1=No   U2=Yes   U3=Yes   R1=Yes   R2=No   R3=No", "",
            "TABLE:  \"LOAD PATTERN DEFINITIONS\"",
            "   LoadPat=LIVE   DesignType=Live   SelfWtMult=0", "",
            "TABLE:  \"JOINT LOADS - FORCE\"",
            F("   Joint=2   LoadPat=LIVE   CoordSys=GLOBAL   F1=0   F2=0   F3={0}   M1=0   M2=0   M3=0", -P), "",
            "TABLE:  \"LOAD CASE DEFINITIONS\"",
            "   Case=LIVE   Type=LinStatic   InitialCond=Zero", "",
            "TABLE:  \"CASE - STATIC 1 - LOAD ASSIGNMENTS\"",
            "   Case=LIVE   LoadType=\"Load pattern\"   LoadName=LIVE   LoadSF=1", "",
            "END TABLE DATA", ""
        };
        File.WriteAllText(path, string.Join("\r\n", lines));
    }

    public string Version() { string v = ""; double n = 0; Check(Model.GetVersion(ref v, ref n), "GetVersion"); return v; }

    public void Open(string s2k)
    {
        Check(Model.File.OpenFile(s2k), "OpenFile " + s2k);
        Check(Model.File.Save(Path.ChangeExtension(s2k, ".sdb")), "Save");   // RunAnalysis needs a saved model
    }

    public void Run()
    {
        Check(Model.Analyze.RunAnalysis(), "RunAnalysis");
        Check(Model.Results.Setup.DeselectAllCasesAndCombosForOutput(), "Deselect");
        Check(Model.Results.Setup.SetCaseSelectedForOutput("LIVE"), "SetCaseSelectedForOutput");
    }

    // Joint displacements (joint local axes), all joints, selected cases -> TSV.
    public string JointDisplacements()
    {
        int n = 0;
        string[] obj = null, elm = null, cas = null, step = null;
        double[] stepNum = null, u1 = null, u2 = null, u3 = null, r1 = null, r2 = null, r3 = null;
        Check(Model.Results.JointDispl("ALL", eItemTypeElm.GroupElm, ref n, ref obj, ref elm, ref cas, ref step,
              ref stepNum, ref u1, ref u2, ref u3, ref r1, ref r2, ref r3), "JointDispl");
        List<string> rows = new List<string>();
        rows.Add("Joint\tOutputCase\tU1\tU2\tU3\tR1\tR2\tR3");
        for (int i = 0; i < n; i++)
            rows.Add(F("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}", obj[i], cas[i], u1[i], u2[i], u3[i], r1[i], r2[i], r3[i]));
        return string.Join("\r\n", rows) + "\r\n";
    }

    // Frame forces (frame local axes) at every output station, selected cases -> TSV.
    public string FrameForces()
    {
        int n = 0;
        string[] obj = null, elm = null, cas = null, step = null;
        double[] objSta = null, elmSta = null, stepNum = null, p = null, v2 = null, v3 = null, t = null, m2 = null, m3 = null;
        Check(Model.Results.FrameForce("ALL", eItemTypeElm.GroupElm, ref n, ref obj, ref objSta, ref elm, ref elmSta,
              ref cas, ref step, ref stepNum, ref p, ref v2, ref v3, ref t, ref m2, ref m3), "FrameForce");
        List<string> rows = new List<string>();
        rows.Add("Frame\tStation\tOutputCase\tP\tV2\tV3\tT\tM2\tM3");
        for (int i = 0; i < n; i++)
            rows.Add(F("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}\t{8}", obj[i], objSta[i], cas[i], p[i], v2[i], v3[i], t[i], m2[i], m3[i]));
        return string.Join("\r\n", rows) + "\r\n";
    }

    public string Probe()
    {
        int n = 0; string[] a = null;
        Model.LoadCases.GetNameList(ref n, ref a); string cases = n + ": " + string.Join(",", a ?? new string[0]);
        n = 0; a = null; Model.PointObj.GetNameList(ref n, ref a); string joints = n + ": " + string.Join(",", a ?? new string[0]);
        return "file=" + Model.GetModelFilename(true) + " cases=" + cases + " joints=" + joints;
    }

    public void Close() { if (Started) Sap.ApplicationExit(false); }

    static string F(string fmt, params object[] args) { return string.Format(Inv, fmt, args); }
    static void Check(int ret, string what) { if (ret != 0) throw new Exception(what + " returned " + ret); }
}
